apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
  labels:
    app: gcp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-gke
        image: gcr.io/playground-s-11-b93e5e8f/gcpdevops:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
